# 作業1-水果資料集Dataset和Dataloader
Github上有一個水果資料集<br>
[水果資料集](https://github.com/TommyHuang821/NTUT_Course/blob/main/NTUT_111-1/Code/dataset/Example_fruit.zip)


## Q1.	請利用課程教的dataset宣告方式寫出pytorch私有資料庫(class 宣告)的讀取方式。

In [38]:
# Q1: code here

from google.colab import drive
drive.mount('/content/drive')
import json
classnames = ['Apple','Banana','Watermelon']  
import os
import numpy as np
import torch
import numpy as np
import PIL.Image as Image
import torchvision.transforms.functional as FT
from torchvision import transforms

imagepaths, labels=[],[]
for dirname, _, filenames in os.walk('/content/drive/MyDrive/dataset/Train'):
    fruitname = dirname.split("//")[-1]
    label = -1
    if fruitname=='/content/drive/MyDrive/dataset/Train/Apple':
        label = 0
    elif fruitname=='/content/drive/MyDrive/dataset/Train/Banana':
        label = 1
    elif fruitname=='/content/drive/MyDrive/dataset/Train/Watermelon':
        label = 2
    for filename in filenames:
        imagepaths.append(os.path.join(dirname, filename))
        labels.append(label)
    
print(imagepaths[0])
print(labels)
print(len(imagepaths))
print(len(labels))

data={}
data['imagepaths']=imagepaths
data['labels'] = labels
with open('/content/drive/MyDrive/dataset/data_fruit.json', 'w', newline='') as jsonfile:
    json.dump(data, jsonfile)
mytransform=transforms.Compose([
        transforms.Resize((224,224)),
        transforms.ToTensor(),
        ])    
class MyDataset(torch.utils.data.Dataset):
    '''
    Class to load the dataset
    '''
    def __init__(self,transforms):
        
        with open('/content/drive/MyDrive/dataset/data_fruit.json') as jsonfile:
            data_load = json.load(jsonfile)
        self.imList = data_load['imagepaths']
        self.labelList = data_load['labels']
        self.transforms=transforms
        print('number of total data:{}'.format(len(self.imList)))
    def __len__(self):
        return len(self.imList)

    def __getitem__(self, idx):
        '''
        :param idx: Index of the image file
        :return: returns the image and corresponding label file.
        '''
        image_name = self.imList[idx]
        label = self.labelList[idx]
        
        # read image with PIL module
        image = Image.open(image_name, mode='r')
        image = image.convert('RGB')
    
        
        # Convert PIL label image to torch.Tensor
        image = self.transforms(image)
        label = torch.tensor(label)
        return image, label

if __name__ == "__main__":
    mydataset = MyDataset(transforms=mytransform)
    mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=10, num_workers=0)
    for data in mydata_loader:
        
        print(data[0].size())
        print(data[1].size())
#         print(imagepath)
        break    

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/dataset/Train/Watermelon/20_100.jpg
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
139
139
number of total data:139
torch.Size([10, 3, 224, 224])
torch.Size([10])


## Q2.	嘗試用pytorch dataloader讀資料，並設定batch = 1, 3, 5, 7。


In [39]:
# Q2: code here

mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=1, num_workers=0)
count = 0
for data, target in mydata_loader: 
    count+=1
print(data.size())  # batch * channel * h * w
print(target.size()) # batch
print("total iterations: {}".format(count))

mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=3, num_workers=0)
count = 0
for data, target in mydata_loader:
    count+=1
print("total iterations: {}".format(count))

mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=5, num_workers=0)
count = 0
for data, target in mydata_loader:
    count+=1
print("total iterations: {}".format(count))

mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=7, num_workers=0)
count = 0
for data, target in mydata_loader:
    count+=1
print("total iterations: {}".format(count))


torch.Size([1, 3, 224, 224])
torch.Size([1])
total iterations: 139
total iterations: 47
total iterations: 28
total iterations: 20


## Q3.	執行Shuffle=True 和False在batch = 10，並說明兩者的差異。


In [40]:
# Q2: code here

mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=10, shuffle=False)
print("first epoch")
for i, (data, target) in enumerate(mydata_loader):
    print(target)
    if i>10:
        break
print("Second epoch")
for i, (data, target) in enumerate(mydata_loader):
    print(target)
    if i>10:
        break


first epoch
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Second epoch
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([2, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


當 Shuffle = False時，
見上面結果，可以發現兩個epoch得到的batch資料結果是一樣的。


In [41]:
mydata_loader = torch.utils.data.DataLoader(mydataset, batch_size=10, shuffle=True)
print("first epoch")
for i, (data, target) in enumerate(mydata_loader):
    print(target)
    if i>10:
        break
print("Second epoch")
for i, (data, target) in enumerate(mydata_loader):
    print(target)
    if i>10:
        break

first epoch
tensor([2, 0, 2, 0, 2, 1, 2, 2, 1, 0])
tensor([1, 1, 1, 2, 0, 0, 1, 2, 2, 1])
tensor([2, 0, 0, 0, 1, 1, 0, 2, 0, 0])
tensor([2, 2, 1, 2, 1, 2, 1, 0, 2, 0])
tensor([0, 1, 1, 0, 0, 0, 0, 2, 0, 1])
tensor([1, 0, 0, 0, 2, 0, 1, 2, 0, 0])
tensor([0, 2, 2, 2, 1, 2, 2, 2, 2, 0])
tensor([1, 2, 0, 1, 0, 2, 2, 0, 0, 2])
tensor([0, 2, 1, 1, 1, 2, 2, 0, 1, 1])
tensor([1, 2, 2, 2, 2, 1, 1, 1, 0, 2])
tensor([2, 2, 0, 0, 1, 2, 2, 0, 1, 2])
tensor([0, 0, 2, 0, 1, 0, 0, 0, 2, 2])
Second epoch
tensor([0, 0, 1, 0, 2, 2, 2, 0, 2, 0])
tensor([1, 1, 2, 1, 1, 1, 2, 0, 0, 0])
tensor([1, 1, 0, 2, 0, 2, 0, 0, 1, 0])
tensor([0, 1, 0, 2, 2, 2, 0, 2, 0, 0])
tensor([1, 1, 2, 2, 0, 0, 2, 0, 1, 1])
tensor([2, 2, 2, 0, 0, 0, 0, 1, 0, 2])
tensor([1, 0, 2, 1, 2, 2, 0, 2, 2, 0])
tensor([2, 0, 1, 2, 2, 0, 1, 0, 2, 1])
tensor([2, 1, 2, 1, 0, 0, 2, 2, 2, 2])
tensor([1, 2, 1, 1, 2, 2, 2, 2, 0, 2])
tensor([0, 2, 1, 0, 1, 1, 0, 1, 2, 0])
tensor([1, 0, 1, 0, 2, 2, 1, 2, 2, 0])


當 Shuffle = True，
見上面結果，可以發現兩個epoch第一次得到的資料結果是不一樣的。
要避免每一個epoch都學習一樣的順序和一樣的batch時候Shuffle就需要設定為True 
這樣資料在每個epoch的時候，每個batch的組合都會重新打亂，這樣訓練模型過程中可以避免每個epoch都是在學習固定的。